### ISSUE TITLE
Float Precision

### ISSUE THREAD

**Issue by reflog** [pmndrs/react-three-editor#43]
Hi!
Quick question - is it possible to set the precision for the float input fields? Right now it seems to round the numbers to one digit after the dot. Cannot enter 0.001 for example.

Thanks in advance and kudos on an amazing project!

**Comment by krispya** [comment]
It uses leva so it is possible with the `pad` property. We could hook it into a setting, but also I think we should support 4 decimal places like Unreal does by default.

**Comment by reflog** [comment]
Thanks @krispya . Any pointers to where I can tweak the pad property in reac-three-editor's code?

**Comment by krispya** [comment]
I'm not 100% certain. I think somewhere in ElementControls but I'd have to break it down to see exactly where to inject `pad`. https://github.com/pmndrs/react-three-editor/blob/main/packages/three-fiber/src/ElementControls.tsx

Maybe @nksaraf knows.

**Comment by nksaraf** [comment]
Yeah so each property control is added via plug-ins.. So for example all the 3D objects get the transform controls fro this control type, etc. the position/rotation/scale comes from: https://github.com/pmndrs/react-three-editor/blob/main/packages/three-fiber/src/prop-types/transform.tsx

**Comment by reflog** [comment]
perfect. thanks guys!
