### ISSUE TITLE
proposal: extract the scene graph out from leva to different component

### ISSUE THREAD

**Issue by dineshsalunke** [pmndrs/react-three-editor#7]
Ideally it would be really intuitive if the scene graph sits outside of the leva panel into as its own UI.

Reasons: 
- Leva panel is properties inspector, so it might slowly grow to include many other properties for the elements.
- The scene hierarchy in many cases will be long and navigating through it on the leva panel will become a bit tedious

@nksaraf any specific reason to have the scene graph in the leva panel ?

**Comment by nksaraf** [comment]
No particular scene apart from just didn't do the setup for multi panel setups .. I want to have to a way of persisting positions of the panel and maybe some configurability of the panel.

But otherwise it makes sense to have separate panels.

**Comment by nksaraf** [comment]
I think ive finally landed on an architecture and separation that makes sense! your starting the refactor was very helpful.

As per configurability, I meant, being able to drag it out of the main panel into separate panels and being able to merge it back. Need to hack `leva` a bit for that.
